--------------------------------------------------------
--  File created - Friday-March-13-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CONTACTS_NOTES
--------------------------------------------------------

  CREATE TABLE "HR"."CONTACTS_NOTES" 
   (	"CONTACT_ID" NUMBER(6,0), 
	"FIRST_NAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(25 BYTE), 
	"FIDELITY_NUM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into HR.CONTACTS_NOTES
SET DEFINE OFF;
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (1,'Clarinda','Nolette','CI405172');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (2,'Bernd','Sebree','CI925159');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (3,'Arlene','Hakimi','CI571668');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (4,'Thaddeus','Politowski','CI409647');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (5,'Githa','Tumaneng','CI815718');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (6,'Hyacinthe','Madnick','CI209415');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (7,'Ignace','Wojick','CI903725');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (8,'Aniruddha','Macmullan','CI870531');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (9,'Verena','Skender','CI912474');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (10,'Barbra','Proch','CI450650');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (11,'Sherley','Campton','CI252221');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (12,'Heath','Mordan','CI832815');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (13,'Ismail','Rippstein','CI386978');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (14,'Lucio','Bodnar','CI410644');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (15,'Lianne','Talburt','CI562981');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (16,'Seb','Dibenedetto','CI915145');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (17,'Verity','Lorna','CI269170');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (18,'Kaitlynn','Tamaro','CI574298');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (19,'Ridge','Samiento','CI530177');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (20,'Ashlee','Pechin','CI256466');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (21,'Hipolito','Felber','CI915121');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (22,'Jazmin','Demshar','CI740205');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (23,'Colette','Albert','CI341264');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (24,'Eddy','Traugott','CI830975');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (25,'Rock','Postuci','CI227791');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (26,'Alonzo','Henegan','CI807640');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (27,'Garrick','Krivanec','CI772469');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (28,'Bell','Koetje','CI407991');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (29,'Divina','Wesner','CI567301');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (30,'Lauro','Romesburg','CI764664');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (31,'Lurdes','Drullard','CI847448');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (32,'Etha','Atcheson','CI561235');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (33,'Neil','Freguson','CI403434');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (34,'Suraj','Suggett','CI864788');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (35,'Nawal','Grubba','CI586721');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (36,'Winnifred','Viator','CI760382');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (37,'Ernie','Kirtdoll','CI254470');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (38,'Cyrilla','Leith','CI413689');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (39,'Trista','Rumbach','CI586446');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (40,'Siegfried','Gachupin','CI646670');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (41,'Kirby','Russer','CI317303');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (42,'Hani','Bruck','CI830563');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (43,'Elijah','Pierzchala','CI608984');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (44,'Crescenzo','Binienda','CI709648');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (45,'Larrie','Asante','CI604551');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (46,'Leon','Pfautz','CI539881');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (47,'Bettina','Rosener','CI571808');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (48,'Werner','Weinert','CI345784');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (49,'Jeri','Hardesty','CI657642');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (50,'Hafsah','Egelston','CI630580');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (51,'Liberatore','Klingenberger','CI959963');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (52,'Alfonsina','Mayotte','CI430731');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (53,'Myron','Whittman','CI613698');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (54,'Emmeline','Bischof','CI858712');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (55,'Stanley','Pentilow','CI386267');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (56,'Nick','Jellinek','CI469518');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (57,'Terrell','Schnabel','CI779808');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (58,'Robby','Kiddle','CI975149');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (59,'Brandi','Zike','CI445188');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (60,'Gabe','Liverani','CI868960');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (61,'Ayla','Benvenuti','CI868308');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (62,'Friede','Laura','CI602961');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (63,'Rogelio','Mcintrye','CI256698');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (64,'Hamid','Beyale','CI274265');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (65,'Jessenia','Kolodziej','CI661920');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (66,'Leonor','Branaman','CI518665');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (67,'Nanda','Gaunce','CI660971');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (68,'Konrad','Sypult','CI380297');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (69,'Tacito','Raygoza','CI906837');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (70,'Louann','Vogt','CI240987');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (71,'Lashonda','Rothell','CI404975');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (72,'Piedad','Angileri','CI903696');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (73,'Lavera','Brunkow','CI305980');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (74,'Timothee','Knepp','CI470785');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (75,'Kiara','Tsuda','CI430323');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (76,'Alessia','Clonts','CI785643');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (77,'Cristina','Leuenberger','CI907461');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (78,'Yasmin','Varoz','CI812931');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (79,'Nasir','Swiger','CI763348');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (80,'Digby','Amiri','CI787643');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (81,'Tolly','Mulhall','CI323642');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (82,'Gladwyn','Lindley','CI603126');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (83,'Mahendra','Bracamonte','CI719874');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (84,'Sefu','Polhamus','CI458729');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (85,'Winfried','Flinders','CI443335');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (86,'Linford','Pacek','CI302300');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (87,'Loyce','Benzie','CI807942');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (88,'Husam','Devino','CI283235');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (89,'Adolphus','Craawford','CI774266');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (90,'Zahrah','Unzicker','CI551539');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (91,'Arlen','Cassata','CI250259');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (92,'Jonah','Agan','CI270466');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (93,'Baptist','Lessley','CI509243');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (94,'Lovel','Dowda','CI907834');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (95,'Renato','Drzewicki','CI848173');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (96,'Daphne','Engelson','CI814589');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (97,'Lexie','Llarena','CI217493');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (98,'Silvester','Mova','CI919602');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (99,'Nolan','Mickus','CI251982');
Insert into HR.CONTACTS_NOTES (CONTACT_ID,FIRST_NAME,LAST_NAME,FIDELITY_NUM) values (100,'Winter','Vandiest','CI309154');
